version: '3'

services:
    nginx:
        build:
            context: ./
            dockerfile: ./docker/nginx/Dockerfile
        depends_on:
            - php-fpm
        ports:
            - 8080:80
        environment:
            - NGINX_HOST=sample-app.dev
            - NGINX_PORT=80
            - FPM-PORT=9000
        volumes:
            - .:/var/www
    php-fpm:
        build:
            context: ./
            dockerfile: ./docker/php-fpm/Dockerfile
        volumes:
            - .:/var/www
