version: '2'

volumes:
    logs:
        driver: local

services:
    sample-app:
        image: php:7-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public public/index.php
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - var/logs:/var/www/logs
